"""add_file_hash_and_raw_text_to_resumes_raw

Revision ID: 1f9b675419a8
Revises: 625c9b53db06
Create Date: 2026-07-10 22:02:18.455363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f9b675419a8'
down_revision: Union[str, None] = '625c9b53db06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('resumes_raw', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('resumes_raw', sa.Column('raw_text', sa.Text(), nullable=True))
    op.create_index('ix_resumes_raw_file_hash', 'resumes_raw', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index('ix_resumes_raw_file_hash', table_name='resumes_raw')
    op.drop_column('resumes_raw', 'raw_text')
    op.drop_column('resumes_raw', 'file_hash')
    # ### end Alembic commands ###
