"""create_jd_cache_table

Revision ID: 21b5dbf7e53a
Revises: 1f9b675419a8
Create Date: 2026-07-10 22:38:37.907200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21b5dbf7e53a'
down_revision: Union[str, None] = '1f9b675419a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('jd_cache',
        sa.Column('jd_hash', sa.String(length=64), nullable=False),
        sa.Column('normalized_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('jd_hash')
    )
    op.create_index('ix_jd_cache_jd_hash', 'jd_cache', ['jd_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_index('ix_jd_cache_jd_hash', table_name='jd_cache')
    op.drop_table('jd_cache')
    # ### end Alembic commands ###
