# Error Code Constants
ERROR_NOT_FOUND = "NOT_FOUND"
ERROR_VALIDATION = "VALIDATION_ERROR"
ERROR_AI_SERVICE = "AI_SERVICE_ERROR"
ERROR_STORAGE = "STORAGE_ERROR"
ERROR_UNAUTHORIZED = "UNAUTHORIZED"
ERROR_RATE_LIMIT = "RATE_LIMIT_EXCEEDED"
ERROR_VECTOR_DB = "VECTOR_DB_ERROR"
ERROR_INTERNAL = "INTERNAL_ERROR"

# Score Buckets
SCORE_BUCKET_POOR = "0-30"
SCORE_BUCKET_AVERAGE = "30-60"
SCORE_BUCKET_GOOD = "60-80"
SCORE_BUCKET_EXCELLENT = "80-100"

# Experience Levels
EXP_LEVEL_JUNIOR = "Junior"
EXP_LEVEL_MID = "Mid-level"
EXP_LEVEL_SENIOR = "Senior"
EXP_LEVEL_EXPERT = "Expert"
