from __future__ import annotations

from typing import TYPE_CHECKING
import uuid

from sqlalchemy import Float, ForeignKey, Integer, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampMixin

if TYPE_CHECKING:
    from .candidate import Candidate
    from .evaluation import Evaluation


class InterviewSession(Base, TimestampMixin):
    """One interview-prep run for a candidate, optionally tied to a specific evaluation."""

    __tablename__ = "interview_sessions"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    candidate_id: Mapped[int] = mapped_column(ForeignKey("candidates_parsed.id", ondelete="CASCADE"))
    evaluation_id: Mapped[int | None] = mapped_column(ForeignKey("evaluations.id", ondelete="SET NULL"))

    status: Mapped[str] = mapped_column(String(20), default="IN_PROGRESS")  # IN_PROGRESS / COMPLETED / ABANDONED

    # Final Report Fields
    average_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    confidence_feedback: Mapped[str | None] = mapped_column(Text, nullable=True)
    suggestions: Mapped[str | None] = mapped_column(Text, nullable=True) # JSON array of suggestions
    strengths: Mapped[str | None] = mapped_column(Text, nullable=True) # JSON array of strengths

    candidate: Mapped["Candidate"] = relationship(back_populates="interview_sessions")
    evaluation: Mapped["Evaluation | None"] = relationship(back_populates="interview_sessions")
    questions: Mapped[list["InterviewQuestion"]] = relationship(
        back_populates="session", cascade="all, delete-orphan", order_by="InterviewQuestion.question_order"
    )


class InterviewQuestion(Base, TimestampMixin):
    """A single question generated by the Interview Prep Agent, with adaptive difficulty."""

    __tablename__ = "interview_questions"

    id: Mapped[int] = mapped_column(primary_key=True)
    session_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("interview_sessions.id", ondelete="CASCADE"))

    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    difficulty_level: Mapped[str] = mapped_column(String(10), default="MEDIUM")  # EASY / MEDIUM / HARD
    question_order: Mapped[int] = mapped_column(Integer, nullable=False)

    session: Mapped["InterviewSession"] = relationship(back_populates="questions")
    answer: Mapped["InterviewAnswer | None"] = relationship(
        back_populates="question", uselist=False, cascade="all, delete-orphan"
    )


class InterviewAnswer(Base, TimestampMixin):
    """Candidate's answer + Interview Evaluation Agent's feedback and follow-up."""

    __tablename__ = "interview_answers"

    id: Mapped[int] = mapped_column(primary_key=True)
    question_id: Mapped[int] = mapped_column(
        ForeignKey("interview_questions.id", ondelete="CASCADE"), unique=True
    )

    answer_text: Mapped[str] = mapped_column(Text, nullable=False)
    feedback_text: Mapped[str | None] = mapped_column(Text)
    score: Mapped[float | None] = mapped_column(Float)  # e.g. 0-10
    follow_up_question: Mapped[str | None] = mapped_column(Text)

    question: Mapped["InterviewQuestion"] = relationship(back_populates="answer")